# ============================================
# FRAMEWORK CONFIGURATION
# ============================================

# Browser: chrome, firefox, edge
browser=chrome

url=https://www.saucedemo.com

headless=false

implicitWait=10
explicitWait=20