# ============================================
# FRAMEWORK CONFIGURATION
# ============================================

# Browser: chrome, firefox, edge
browser=chrome

url=https://www.saucedemo.com

headless=false

#standard data for checkout page
firstname = testfirst
lastname = testlast
zipcode = 110027